# Generated by Django 3.0.8 on 2021-06-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiami_seckill_backend', '0002_user_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='test',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
