# Generated by Django 3.0.8 on 2021-06-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiami_seckill_backend', '0003_auto_20210626_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='test',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
