# Generated by Django 3.0.8 on 2021-06-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiami_seckill_backend', '0004_auto_20210626_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='test',
            new_name='mobile',
        ),
        migrations.AddField(
            model_name='user',
            name='payment_pwd',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
