# Generated by Django 3.0.8 on 2021-06-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiami_seckill_backend', '0006_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.CharField(default='100', max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
    ]
