# Generated by Django 3.0.8 on 2021-06-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiami_seckill_backend', '0007_auto_20210626_1056'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='tbl_user',
        ),
    ]
