# Generated by Django 3.0.8 on 2021-06-26 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiami_seckill_backend', '0008_auto_20210626_1432'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='aaa_user',
        ),
    ]
