# Generated by Django 3.2.5 on 2021-07-31 12:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('xiami_seckill_backend', '0010_auto_20210626_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='JDUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('nick_name', models.CharField(max_length=20)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=20)),
                ('full_addr', models.CharField(blank=True, default='', max_length=500)),
                ('mobile', models.CharField(blank=True, default='', max_length=20)),
                ('pc_cookie_status', models.BooleanField(default=False)),
                ('pc_cookie_str', models.TextField(blank=True, default='')),
                ('pc_cookie_ts', models.CharField(blank=True, default='', max_length=100)),
                ('pc_cookie_ts_label', models.CharField(blank=True, default='', max_length=100)),
                ('pc_cookie_expire_ts', models.CharField(blank=True, default='', max_length=100)),
                ('pc_cookie_expire_ts_label', models.CharField(blank=True, default='', max_length=100)),
                ('mobile_cookie_status', models.BooleanField(default=False)),
                ('mobile_cookie_str', models.TextField(blank=True, default='')),
                ('mobile_cookie_ts', models.CharField(blank=True, default='', max_length=100)),
                ('mobile_cookie_ts_label', models.CharField(blank=True, default='', max_length=100)),
                ('mobile_cookie_expire_ts', models.CharField(blank=True, default='', max_length=100)),
                ('mobile_cookie_expire_ts_label', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiami_seckill_backend.user')),
            ],
            options={
                'db_table': 'tbl_jd_user',
                'abstract': False,
            },
        ),
    ]
