# Generated by Django 3.2.5 on 2021-08-02 09:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('xiami_seckill_backend', '0011_jduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='JDOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('order_time', models.CharField(max_length=50)),
                ('order_id', models.CharField(max_length=50)),
                ('sum_price', models.CharField(max_length=20)),
                ('addr_name', models.CharField(max_length=50)),
                ('addr', models.CharField(max_length=500)),
                ('item_info_array', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xiami_seckill_backend.user')),
            ],
            options={
                'db_table': 'tbl_jd_order',
                'abstract': False,
            },
        ),
    ]
