# Generated by Django 3.2.5 on 2021-08-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiami_seckill_backend', '0012_jdorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdorder',
            name='nick_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
