# Generated by Django 3.2.5 on 2021-08-03 12:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('xiami_seckill_backend', '0013_jdorder_nick_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='JDUserArrangement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('seckill_arrangement', models.TextField()),
                ('sku_arrangement', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xiami_seckill_backend.user')),
            ],
            options={
                'db_table': 'tbl_jd_user_arrangement',
                'abstract': False,
            },
        ),
    ]
