# Generated by Django 3.2.5 on 2021-08-05 07:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('xiami_seckill_backend', '0014_jduserarrangement'),
    ]

    operations = [
        migrations.CreateModel(
            name='JDUserOptions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('leadming_time', models.CharField(max_length=10)),
                ('jd_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xiami_seckill_backend.jduser')),
            ],
            options={
                'db_table': 'tbl_jd_user_options',
                'abstract': False,
            },
        ),
    ]
