# Generated by Django 3.2.5 on 2021-08-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiami_seckill_backend', '0015_jduseroptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='jduser',
            name='leading_time',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='JDUserOptions',
        ),
    ]
