# Generated by Django 3.2.5 on 2021-08-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiami_seckill_backend', '0016_auto_20210805_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='jduser',
            name='jd_pwd',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jduser',
            name='push_token',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
