# Generated by Django 3.2.5 on 2021-08-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiami_seckill_backend', '0017_auto_20210808_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jduser',
            name='jd_pwd',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='jduser',
            name='push_token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
