# Generated by Django 3.2.5 on 2021-08-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiami_seckill_backend', '0018_auto_20210808_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='jduser',
            name='push_email',
            field=models.TextField(blank=True, default=''),
        ),
    ]
