# Generated by Django 3.2.5 on 2021-08-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiami_seckill_backend', '0019_jduser_push_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdorder',
            name='is_oversea',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jdorder',
            name='is_presale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jdorder',
            name='is_reserve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jdorder',
            name='is_seckill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jdorder',
            name='leading_time',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
