# Generated by Django 3.2.5 on 2021-08-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiami_seckill_backend', '0020_auto_20210810_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jdorder',
            name='is_oversea',
            field=models.CharField(blank=True, default='否', max_length=10),
        ),
        migrations.AlterField(
            model_name='jdorder',
            name='is_presale',
            field=models.CharField(blank=True, default='否', max_length=10),
        ),
        migrations.AlterField(
            model_name='jdorder',
            name='is_reserve',
            field=models.CharField(blank=True, default='否', max_length=10),
        ),
        migrations.AlterField(
            model_name='jdorder',
            name='is_seckill',
            field=models.CharField(blank=True, default='否', max_length=10),
        ),
    ]
