# Generated by Django 3.2.5 on 2021-08-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiami_seckill_backend', '0021_auto_20210810_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jdorder',
            name='is_oversea',
        ),
        migrations.RemoveField(
            model_name='jdorder',
            name='is_presale',
        ),
        migrations.AlterField(
            model_name='jdorder',
            name='is_reserve',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='jdorder',
            name='is_seckill',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
