# Generated by Django 3.2.5 on 2021-08-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiami_seckill_backend', '0024_auto_20210811_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jdorder',
            name='current_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='jdorder',
            name='original_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='jdorder',
            name='saved_price',
            field=models.FloatField(default=0),
        ),
    ]
