# Generated by Django 3.2.5 on 2021-08-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiami_seckill_backend', '0025_auto_20210811_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='payment_pwd',
        ),
    ]
