# Generated by Django 3.2.5 on 2021-08-11 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiami_seckill_backend', '0026_auto_20210811_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jduserarrangement',
            name='sku_arrangement',
        ),
    ]
