# Generated by Django 3.2.5 on 2021-08-12 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiami_seckill_backend', '0027_remove_jduserarrangement_sku_arrangement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jdorder',
            old_name='current_price',
            new_name='target_price',
        ),
    ]
