# Generated by Django 3.2.5 on 2021-08-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiami_seckill_backend', '0028_rename_current_price_jdorder_target_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='jduser',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
